### ISSUE TITLE
Two FPs

### ISSUE THREAD

**Issue by sr093906** [oo12/SMBBB#1]
www.baidu.com: a search engine focusing on Chinese-language 

lib.tnua.edu.tw: online library of Taipei National University of the Arts

**Comment by oo12** [comment]
Thanks! These were both on the list because of open redirect vulnerabilities on those sites, which I've seen used in phishing campaigns. The Taipei National University of the Arts one was back in 2021 and has since been fixed, so I removed it from the list.

For Baidu, the last phishing link we got using them was more recent, from fall of 2023. That link is still active, though the site it redirects to no longer hosts the phishing page it used to. I'll remove www.baidu.com too, since I've only seen it used that once in phishing emails, and it's a major site for part of the world at least.
